version: '3.8'           # docker-compose 버전

services:
  backend:
    build: ./backend     # backend Dockerfile 위치
    ports:
      - "8080:8080"      # 외부:내부 포트
    environment:         # 환경변수 설정
      - SPRING_PROFILES_ACTIVE=dev
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:          # 의존성 설정
      - mysql

  frontend:
    build: ./frontend    # frontend Dockerfile 위치
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  mysql:
    image: mysql:8.0.4     # MySQL 이미지
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=conkiri
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "13309:3306"
    volumes:            # 데이터 영속성
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:          # MySQL 데이터 저장용 볼륨