spring:
  profiles:
    active:
      - local
    group:
      local:
        - oauth
        - db-local
        - cloud
      dev:
        - oauth
        - db-dev
        - cloud
    include: oauth, db, cloud

